apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  secret.json: |-
    {
      "api_key" : "somesecretgoeshere"
    }

#kubectl create secret generic mysecret --from-file .\golang\secrets\secret.json