{
 "title": "OpenTelemetry for HTTP services",
 "description": "RED Metrics and correlation between metrics logs and traces for HTTP services instrumented with OpenTelemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service_namespace",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count,job)"
    }
   },
   {
    "name": "service_name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=~\"${service_namespace}.*\"},exported_job)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"${service_namespace}\"},job)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{job=\"$job\"},http_route)"
    }
   },
   {
    "name": "rateinterval",
    "query": "1m,2m,3m,5m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "predictive_interval", "query": "1h,2h,6h,12h,1d,2d,3d,1w" },
   { "name": "predictive_offset", "query": "1h,2h,6h,12h,1d,2d,3d,1w" }
  ]
 },
 "panels": [
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance metrics overview per service during selected time range",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(http_route)(rate(http_server_request_duration_seconds_count{job=\"$service_name\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (http_route) (increase(http_server_request_duration_seconds_sum{job=\"$service_name\",http_route=~\"$http_route\"}[$__range])) / sum by(http_route)(increase(http_server_request_duration_seconds_count{job=\"$service_name\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$service_name\",http_route=~\"$http_route\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route)(increase(http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(http_route) (http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\",http_response_status_code=~\"2.*\"}) / sum by(http_route) (http_server_request_duration_seconds_count{job=\"$job\",http_route=~\"$http_route\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 per endpoint over $rateinterval interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$rateinterval])) by(http_route, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 over selected time range",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$__range])) by(http_route,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time distribution in seconds over selected time range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(http_server_request_duration_seconds_bucket{job=\"$job\",http_route=~\"$http_route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}