
Vagrant.configure("2") do |config|
  
  # server settings
  serverName = ENV['SERVER_NAME']
  sharedFolder = ENV['SERVER_SHAREDFOLDER']
  SERVER_USERNAME = ENV['SERVER_USERNAME']
  SERVER_PASSWORD = ENV['SERVER_PASSWORD']

  #ci settings
  PAT_TOKEN = ENV['PAT_TOKEN']
  GITHUB_ORG = ENV['GITHUB_ORG']
  GITHUB_REPO = ENV['GITHUB_REPO']
  RUNNER_NAME = ENV['RUNNER_NAME']

  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_version = "20250725.0.0"
  config.vm.synced_folder "#{sharedFolder}", "/home/devopsguy/gitrepos"
  
  config.vm.network "private_network", ip: "192.168.56.5"

  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "forwarded_port", guest: 80, host: 8080
  
  # user default user during vm creation. provisioning will create our user.
  config.ssh.insert_key = true
  config.vm.provider "virtualbox" do |vb|
    
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    vb.name = serverName
    vb.memory = "1024"
    vb.cpus = 4
  end
  
  # config.vm.provision "shell" do |s|
  #   s.path = "provision_user.sh"
  #   s.args   = ["#{SERVER_USERNAME}", "#{SERVER_PASSWORD}"]
  # end

  config.vm.provision "file", source: "my-website", destination: "$HOME/tmp/"

  # config.vm.provision "shell" do |s|
  #   s.path = "provision_webserver.sh"
  # end

  # config.vm.provision "shell" do |s|
  #   s.path = "../../../../../automation/cicd/ci/examples/github/.test/install-github-runner.sh"
  #   s.args   = ["#{PAT_TOKEN}", "#{GITHUB_ORG}", "#{GITHUB_REPO}", "#{RUNNER_NAME}"]
  # end
  
  config.vm.provision "file", source: "playbook.yaml", destination: "/tmp/playbook.yaml"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yaml"
    ansible.provisioning_path = "/tmp"
    ansible.extra_vars = {
      SERVER_USERNAME: "#{SERVER_USERNAME}",
      SERVER_PASSWORD: "#{SERVER_PASSWORD}",
      PAT_TOKEN: "#{PAT_TOKEN}",
      GITHUB_ORG: "#{GITHUB_ORG}",
      GITHUB_REPO: "#{GITHUB_REPO}",
      RUNNER_NAME: "#{RUNNER_NAME}"
    }
  end

end
