FROM python:3.10.5-alpine3.16 as dev

WORKDIR /work

FROM python:3.10.5-alpine3.16 as debugging

# add a debugger

FROM dev as runtime
COPY ./src/ /app 

ENTRYPOINT [ "python", "/app/app.py" ]
