apiVersion: apps/v1
kind: Deployment
metadata:
  name: videos-api
  labels:
    app: videos-api
spec:
  selector:
    matchLabels:
      app: videos-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: videos-api
    spec:
      containers:
      - name: videos-api
        image: aimvector/jaeger-tracing:videos-api-netcore-1.0.0
        imagePullPolicy : Always
        ports:
        - containerPort: 10010
        env:
        - name: "ENVIRONMENT"
          value: "DEBUG"
        - name: "REDIS_HOST"
          value: "videos-db"
        - name: "REDIS_PORT"
          value: "6379"
        - name: "JAEGER_AGENT_HOST"
          value: "jaeger"
        - name: "JAEGER_AGENT_PORT"
          value: "6831"
        - name: "JAEGER_SERVICE_NAME"
          value: "videos-api"
        - name: "JAEGER_REPORTER_LOG_SPANS"
          value: "true"
        - name: "JAEGER_SAMPLER_TYPE"
          value: "const"
        - name: "JAEGER_PROPAGATION"
          value: "jaeger"
---
apiVersion: v1
kind: Service
metadata:
  name: videos-api
  labels:
    app: videos-api
spec:
  type: ClusterIP
  selector:
    app: videos-api
  ports:
    - protocol: TCP
      name: http
      port: 10010
      targetPort: 10010
---


