FROM python:3.7.3-alpine3.9
RUN mkdir /app
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
ADD . /app/
ENV FLASK_APP=/app/server.py
RUN chmod +x entrypoint.sh
ENTRYPOINT ./entrypoint.sh
EXPOSE 5000