{
 "title": "Application Telemetry (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": ".NET Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(dotnet_request_operations_total[2m])"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dotnet_request_duration_seconds_sum[2m]) / rate(dotnet_request_duration_seconds_count[2m])"
    }
   ]
  },
  { "title": "NodeJS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Request per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_request_operations_total[2m])"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_request_duration_seconds_sum[2m]) / rate(node_request_duration_seconds_count[2m])"
    }
   ]
  },
  {
   "title": "Golang",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "irate(go_request_operations_total[2m])"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 20 },
     "targets": [
      {
       "expr": "rate(go_request_duration_seconds_sum[2m]) / rate(go_request_duration_seconds_count[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Python",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "rate(python_request_duration_seconds_sum[2m]) / rate(python_request_duration_seconds_count[2m])"
      }
     ]
    },
    {
     "title": "Request per Second (Python)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 21 },
     "targets": [
      {
       "expr": "irate(python_request_operations_total[2m])"
      }
     ]
    }
   ]
  }
 ]
}