FROM node:12.4.0-alpine as debug

WORKDIR /work/

COPY ./src/package.json /work/package.json
RUN npm install
RUN npm install -g nodemon

COPY ./src/ /work/

CMD nodemon --inspect=0.0.0.0 server.js

FROM node:12.4.0-alpine as prod

COPY ./src/package.json /work/package.json
RUN npm install

CMD node server.js