apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: mcp-backend-kubernetes
spec:
  mcp:
    targets:
    - name: mcp-k8s
      selector:
        services:
          matchLabels:
            app: mcp-k8s